### PR TITLE
Strong Naming

### PR DESCRIPTION
**Pull request by ScottGuymer**
Added a signing key
Updated InternalsVisibleTo usages to use the public key

### CODE REVIEW

**Comment by ScottGuymer** [comment]
Addresses #55

**Comment by ScottGuymer** [comment]
This is a starter for 10 please let me know if there are any changes in approach you would like me to take.

**Comment by ScottGuymer** [comment]
@phnx47 are you happy with thia approach?

Once we agree an approach i can replicate on the other libs.

**Comment by phnx47** [comment]
@ScottGuymer I will check at weekend

**Pull request merged**
